config/routes.rb
PropertyMgmt::Application.routes.draw do

  resources :buildings, only: [:create, :index, :new, :show]
  resources :owners, only: [:create, :destroy, :index, :new, :show]

  root 'buildings#index'

end

app/models/building.rb
class Building < ActiveRecord::Base
  validates_presence_of :address, :city, :state, :zip_code
  validates_numericality_of :zip_code
  belongs_to :owner

  def ownername
    if self.owner == nil
      nil
    else
      self.owner.name
    end
  end

end

app/models/owner.rb
class Owner < ActiveRecord::Base

  validates_presence_of :first_name, :last_name, :email
  has_many :buildings

  def name
    @name = self.first_name + ' ' + self.last_name
  end

  def buildingsowned
    if self.buildings.empty?
      []
    else
      self.buildings
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController

  def create
    @building = Building.new(params.require(:building).permit(:address, :city, :state, :zip_code, :description, :owner_id))
    if @building.save
      redirect_to @building, notice: 'Building successfully listed.'
    else
      render action: 'new'
    end
  end

  def index
    @buildings = Building.all
  end

  def new
    @building = Building.new
    @states = %w[AL AK AZ AR CA CO CT DE FL GA HI ID IL IN IA KS KY LA ME MD MA MI MN MS MO MT NE NV NH NJ NM NY NC ND OH OK OR PA RI SC SD TN TX UT VT VA WA WV WI WY]
  end

  def show
    @building = Building.find(params[:id])
  end

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController

  def create
    @owner = Owner.new(params.require(:owner).permit(:first_name, :last_name, :email, :company_name))
    if @owner.save
      redirect_to @owner, notice: 'Owner successfully created.'
    else
      render action: 'new'
    end
  end

  def destroy
    @owner = Owner.find(params[:id])
    unless @owner.buildings.empty?
      @owner.buildings.each do |building|
        change = building
        change.owner_id = nil
        change.save
      end
    end
    @owner.destroy
    redirect_to owners_path
  end

  def index
    @owners = Owner.all
  end

  def new
    @owner = Owner.new
  end

  def show
    @owner= Owner.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/buildings/index.html.erb
<h1>Listings Index</h1>
<p><%= link_to "New Listing", new_building_path %> | <%= link_to "Owners Index", owners_path %></p>
<ol>
<% @buildings.each do |building| %>
<li><%= link_to building.address, building %></li>
<% end %>
</ol>

app/views/buildings/new.html.erb
<h1>New Listing</h1>

<%= simple_form_for @building do |f| %>
  <% if @building.errors.any? %>
    <p>Error(s) detected; listing not created.</p>
  <% end %>
  <%= f.input :address, label: 'Street Address' %>
  <%= f.input :city %>
  <%= f.input :state, collection: @states %>
  <%= f.input :zip_code, label: 'Postal Code' %>
  <%= f.association :owner, label_method: :name %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/buildings/show.html.erb
<h1><%= @building.address %></h1>
<p id="notice"><%= notice %></p>
<p><%= @building.city + ' ' + @building.state + ' ' + @building.zip_code %></p>
<p>Description: <%= @building.description %></p>
<p>Owned By: <%= @building.ownername %></p>
<%= link_to 'Index', buildings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PropertyMgmt</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/owners/index.html.erb
<h1>Owners Index</h1>
<p><%= link_to "New Owner", new_owner_path %> | <%= link_to "Listings Index", buildings_path %></p>
<ol>
<% @owners.each do |owner| %>
<li><%= link_to owner.name, owner %></li>
<% end %>
</ol>

app/views/owners/new.html.erb
<h1>New Owner</h1>

<%= simple_form_for @owner do |f| %>
  <% if @owner.errors.any? %>
    <p>Error(s) detected; listing not created.</p>
  <% end %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :company_name %>
  <%= f.button :submit %>
<% end %>

app/views/owners/show.html.erb
<h1><%= @owner.name %></h1>
<p id="notice"><%= notice %></p>
<p><%= @owner.email %></p>
<p><%= @owner.company_name %></p>
<%= button_to "Delete", { action: "destroy", id: @owner.id }, method: :delete, data: { confirm: "Are you sure?" } %>
<p>Properties:</p>
<ul>
<% @owner.buildingsowned.each do |building| %>
<li><%= building.address %></li>
<% end %>
</ul>
<%= link_to 'Index', owners_path %>